/** A middleware function designed to ensure the token being used was generated by the application (prevent CSRF).
 *  Returns false if no token is provided, the token provided is not a string, the string is not decodable or if the json web token string does not pass verification.
 * 
 *      ensureTokenOrigin('sampletoken') => true
 * 
 */
const jwt = require('jsonwebtoken');
const {SECRET_KEY} = require('../config');

const ensureTokenOrigin = (token) => {
    
    if(!token || typeof(token) !== 'string' || !jwt.decode(token)) return false;

    try {
        jwt.verify(token, SECRET_KEY);
        return true;
    } catch(e) {
        return false;
    }
};

module.exports = ensureTokenOrigin;