/** A middleware function designed to ensure the token being used was generated by the application (prevent CSRF).
 *  Returns false if no token is provided, the token provided is not a string, the string is not decodable or if the json web token string does not pass verification.
 * 
 *      ensureTokenOrigin('sampletoken') => true
 * 
 */
const jwt = require('jsonwebtoken');
const {SECRET_KEY} = require('../config');
const ExpressError = require('../helpers/expressError');

const ensureTokenOrigin = (req, res, next) => {
    try {
        const token = req.body._token;

        if(!token) {
            throw new ExpressError(`Must provide a token to access route`, 401)
        }
        else if (!jwt.verify(token, SECRET_KEY)) {
            throw new ExpressError(`Must provide a token that originates from the app`, 401)
        }
        return next();
    } catch (err) {
        err.status = 401;
        return next(err);
    }
}

/*const ensureTokenOrigin = (token) => {
    
    if(!token || typeof(token) !== 'string' || !jwt.decode(token)) return false;

    try {
        jwt.verify(token, SECRET_KEY);
        return true;
    } catch(e) {
        return false;
    }
};*/

module.exports = ensureTokenOrigin;